frr version 9.1
frr defaults traditional
hostname r3
no ipv6 forwarding
log syslog informational
!
! -------------------------------------------------------
! AS300 - R3 (VICTIM AS)
! Legitimately owns 13.0.0.0/24
! Only peers with R2 (AS200) as its upstream transit
! This is the prefix that AS400 will attempt to hijack
! -------------------------------------------------------
!
interface lo
 ip address 3.3.3.3/32
 ip address 13.0.0.1/24
!
interface eth1
 description link-to-R2-AS200-transit
 ip address 10.23.0.2/30
!
router bgp 300
 bgp router-id 3.3.3.3
 no bgp ebgp-requires-policy
 no bgp network import-check
 !
 ! THE VICTIM PREFIX — this is what will be hijacked
 network 13.0.0.0/24
 !
 neighbor 10.23.0.1 remote-as 200
 neighbor 10.23.0.1 description R2-AS200-transit
 neighbor 10.23.0.1 ebgp-multihop 2
 neighbor 10.23.0.1 timers 5 15
 !
 address-family ipv4 unicast
  neighbor 10.23.0.1 activate
 exit-address-family
!
ip route 13.0.0.0/24 null0
!
line vty
!
