frr version 9.1
frr defaults traditional
hostname r2
no ipv6 forwarding
log syslog informational
!
! -------------------------------------------------------
! AS200 - R2 (Transit AS)
! Peers with R1 (AS100) and R3 (AS300)
! Forwards routes between R1 and the victim R3
! Announces: 12.0.0.0/24
! -------------------------------------------------------
!
interface lo
 ip address 2.2.2.2/32
 ip address 12.0.0.1/24
!
interface eth1
 description link-to-R1-AS100
 ip address 10.12.0.2/30
!
interface eth2
 description link-to-R3-AS300-VICTIM
 ip address 10.23.0.1/30
!
router bgp 200
 bgp router-id 2.2.2.2
 no bgp ebgp-requires-policy
 no bgp network import-check
 !
 network 12.0.0.0/24
 !
 neighbor 10.12.0.1 remote-as 100
 neighbor 10.12.0.1 description R1-AS100
 neighbor 10.12.0.1 ebgp-multihop 2
 neighbor 10.12.0.1 timers 5 15
 !
 neighbor 10.23.0.2 remote-as 300
 neighbor 10.23.0.2 description R3-AS300-victim
 neighbor 10.23.0.2 ebgp-multihop 2
 neighbor 10.23.0.2 timers 5 15
 !
 address-family ipv4 unicast
  neighbor 10.12.0.1 activate
  neighbor 10.23.0.2 activate
 exit-address-family
!
ip route 12.0.0.0/24 null0
!
line vty
!
